from datetime import datetime
from typing import Optional, List, Literal, Dict, Any
from beanie import Document
from pydantic import BaseModel, Field


class Milestone(BaseModel):
    """A milestone in the timeline plan."""
    date: str = Field(..., description="Date of milestone (YYYY-MM-DD)")
    label: str = Field(..., description="Milestone label (e.g., 'Foundation', 'Core Topics')")
    target: str = Field(..., description="Target achievement for this milestone")
    tips: str = Field(default="", description="Tips for reaching this milestone")


class TimelinePlan(BaseModel):
    """
    Overall timeline plan showing the journey from start to deadline.
    Provides high-level roadmap with milestones and success criteria.
    """
    goal_title: str = Field(..., description="Overall goal (e.g., task title)")
    days_remaining: int = Field(..., description="Total days from start to deadline")
    milestones: List[Milestone] = Field(default_factory=list, description="Key milestones throughout the plan")
    success_criteria: List[str] = Field(default_factory=list, description="Criteria for successful completion")


class StudyBlock(BaseModel):
    """
    A single study block within a schedule.
    Represents a focused time slot dedicated to a specific concept or activity.
    """
    date: str = Field(..., description="Date of the block (YYYY-MM-DD)")
    start_time: str = Field(..., description="Start time (HH:MM)")
    end_time: str = Field(..., description="End time (HH:MM)")
    subject: str = Field(..., description="Subject for this block")
    concept_title: str = Field(..., description="Concept or topic to study")
    concept_id: Optional[str] = Field(None, description="Reference to Concept document (if matched)")
    type: Literal["study", "break", "review"] = Field(..., description="Type of block: study, break, or review")
    key_points: List[str] = Field(default_factory=list, description="Key points to focus on during this block")


class StudySchedule(Document):
    """
    MongoDB document model for deterministic study schedules.
    Generated by rule engine based on task requirements and matched concepts.
    """

    user_id: str = Field(..., description="ID of the user who owns this schedule")
    task_id: str = Field(..., description="Reference to the Task this schedule is for")
    subject: str = Field(..., min_length=1, max_length=100, description="Subject/course for this schedule")
    deadline: datetime = Field(..., description="Final deadline for the task")
    start_date: str = Field(..., description="Schedule start date (YYYY-MM-DD)")
    end_date: str = Field(..., description="Schedule end date (YYYY-MM-DD)")
    blocks: List[StudyBlock] = Field(default_factory=list, description="List of study blocks scheduled")
    timeline: TimelinePlan = Field(..., description="High-level timeline plan with milestones")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="When schedule was created")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="When schedule was last updated")

    class Settings:
        name = "study_schedules"  # MongoDB collection name

    class Config:
        json_schema_extra = {
            "example": {
                "user_id": "user123",
                "task_id": "task456",
                "subject": "Data Structures",
                "deadline": "2026-03-15T23:59:00",
                "start_date": "2026-03-01",
                "end_date": "2026-03-15",
            }
        }


class SmartSchedule(Document):
    """
    MongoDB document model for AI-generated smart study schedules (Groq/Llama).
    Created via POST /api/schedule/generate-smart with optional file uploads.
    """
    user_id: str = Field(default="", description="ID of the user who owns this schedule")
    task_id: str = Field(..., description="Reference to the Task this schedule is for")
    subject: str = Field(..., description="Subject/course for this schedule")
    title: str = Field(default="", description="Task title")
    deadline: datetime = Field(..., description="Task deadline")
    start_date: str = Field(..., description="Schedule start date (YYYY-MM-DD)")
    end_date: str = Field(..., description="Schedule end date (YYYY-MM-DD)")

    # AI-generated content
    document_summaries: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Per-document AI summaries with key_points and topics"
    )
    ai_summary: str = Field(default="", description="Overall AI study plan overview")
    ai_tips: List[str] = Field(default_factory=list, description="AI study tips")
    extracted_topics: List[str] = Field(default_factory=list, description="Topics extracted from documents")
    sessions: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Day-by-day study sessions with date, topics, duration, focus_level"
    )
    original_filenames: List[str] = Field(default_factory=list, description="Names of uploaded files")

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "smart_schedules"